-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    u_id serial NOT NULL,
    u_email text NOT NULL,
    u_phone text NOT NULL,
    u_first_name text NOT NULL,
    u_last_name text NOT NULL,
    u_password text NOT NULL,
    u_type user_type NOT NULL,
    PRIMARY KEY (u_id),
    UNIQUE (u_email, u_phone)
);

CREATE TABLE IF NOT EXISTS public."Products"
(
    p_id serial NOT NULL,
    p_name text NOT NULL,
    p_price money NOT NULL,
    p_brand_id serial NOT NULL,
    p_category_id serial NOT NULL,
    p_average_rating double precision NOT NULL DEFAULT 0,
    PRIMARY KEY (p_id),
    UNIQUE (p_name)
);

CREATE TABLE IF NOT EXISTS public."Brands"
(
    b_id serial NOT NULL,
    b_name text NOT NULL,
    PRIMARY KEY (b_id),
    UNIQUE (b_name)
);

CREATE TABLE IF NOT EXISTS public."Sections"
(
    s_id serial NOT NULL,
    s_name text NOT NULL,
    PRIMARY KEY (s_id),
    UNIQUE (s_name)
);

CREATE TABLE IF NOT EXISTS public."Categories"
(
    c_id serial NOT NULL,
    c_name text NOT NULL,
    c_parent_category_id serial,
    PRIMARY KEY (c_id),
    UNIQUE (c_name)
);

CREATE TABLE IF NOT EXISTS public."Reviews"
(
    r_id serial NOT NULL,
    r_rating numeric NOT NULL,
    r_comment text NOT NULL,
    r_product_id serial NOT NULL,
    r_user_id serial NOT NULL,
    r_title text NOT NULL,
    r_created_at timestamp without time zone NOT NULL,
    PRIMARY KEY (r_id)
);

CREATE TABLE IF NOT EXISTS public."Adresses"
(
    a_id serial NOT NULL,
    a_adress text NOT NULL,
    a_user_id serial NOT NULL,
    PRIMARY KEY (a_id)
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    o_id serial NOT NULL,
    o_price money NOT NULL,
    o_order_status status NOT NULL,
    o_user_id serial NOT NULL,
    o_adress_id serial NOT NULL,
    o_created_at timestamp without time zone NOT NULL,
    PRIMARY KEY (o_id)
);

CREATE TABLE IF NOT EXISTS public."SectionCategory"
(
    sc_section_id serial NOT NULL,
    sc_category_id serial NOT NULL,
    PRIMARY KEY (sc_section_id, sc_category_id)
);

CREATE TABLE IF NOT EXISTS public."CartItems"
(
    ci_user_id serial NOT NULL,
    ci_product_version_id serial NOT NULL,
    quantity integer NOT NULL,
    PRIMARY KEY (ci_user_id, ci_product_version_id)
);

CREATE TABLE IF NOT EXISTS public."OrderItems"
(
    oi_order_id serial NOT NULL,
    oi_product_version_id serial NOT NULL,
    oi_quantity integer NOT NULL,
    PRIMARY KEY (oi_order_id, oi_product_version_id)
);

CREATE TABLE IF NOT EXISTS public."ProductVersions"
(
    pv_id serial NOT NULL,
    pv_quantity integer NOT NULL DEFAULT 0,
    pv_sku text NOT NULL,
    pv_product_id serial NOT NULL,
    pv_size_id serial NOT NULL,
    pv_color_id serial NOT NULL,
    PRIMARY KEY (pv_id),
    UNIQUE (pv_sku)
);

CREATE TABLE IF NOT EXISTS public."Sizes"
(
    s_id serial NOT NULL,
    s_name text NOT NULL,
    PRIMARY KEY (s_id),
    UNIQUE (s_name)
);

CREATE TABLE IF NOT EXISTS public."Colors"
(
    c_id serial NOT NULL,
    c_name text NOT NULL,
    PRIMARY KEY (c_id),
    UNIQUE (c_name)
);

CREATE TABLE IF NOT EXISTS public."Medias"
(
    m_id serial NOT NULL,
    m_bytes bytea NOT NULL,
    m_file_type text NOT NULL,
    m_file_name text NOT NULL,
    m_product_id serial NOT NULL,
    PRIMARY KEY (m_id),
    UNIQUE (m_file_type, m_file_name)
);

CREATE TABLE IF NOT EXISTS public."OrderTransactions"
(
    ot_o_id serial NOT NULL,
    ot_status status NOT NULL,
    ot_updated_at timestamp without time zone NOT NULL,
    PRIMARY KEY (ot_o_id)
);

ALTER TABLE IF EXISTS public."Products"
    ADD FOREIGN KEY (p_brand_id)
    REFERENCES public."Brands" (b_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Products"
    ADD FOREIGN KEY (p_category_id)
    REFERENCES public."Categories" (c_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Categories"
    ADD FOREIGN KEY (c_parent_category_id)
    REFERENCES public."Categories" (c_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reviews"
    ADD FOREIGN KEY (r_product_id)
    REFERENCES public."Products" (p_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reviews"
    ADD FOREIGN KEY (r_user_id)
    REFERENCES public."Users" (u_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Adresses"
    ADD FOREIGN KEY (a_user_id)
    REFERENCES public."Users" (u_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders"
    ADD FOREIGN KEY (o_user_id)
    REFERENCES public."Users" (u_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders"
    ADD FOREIGN KEY (o_adress_id)
    REFERENCES public."Adresses" (a_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SectionCategory"
    ADD CONSTRAINT "SectionId" FOREIGN KEY (sc_section_id)
    REFERENCES public."Sections" (s_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SectionCategory"
    ADD CONSTRAINT "CategoryId" FOREIGN KEY (sc_category_id)
    REFERENCES public."Categories" (c_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CartItems"
    ADD FOREIGN KEY (ci_product_version_id)
    REFERENCES public."ProductVersions" (pv_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CartItems"
    ADD FOREIGN KEY (ci_user_id)
    REFERENCES public."Users" (u_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrderItems"
    ADD FOREIGN KEY (oi_order_id)
    REFERENCES public."Orders" (o_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrderItems"
    ADD FOREIGN KEY (oi_product_version_id)
    REFERENCES public."ProductVersions" (pv_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ProductVersions"
    ADD FOREIGN KEY (pv_product_id)
    REFERENCES public."Products" (p_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ProductVersions"
    ADD FOREIGN KEY (pv_size_id)
    REFERENCES public."Sizes" (s_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ProductVersions"
    ADD FOREIGN KEY (pv_color_id)
    REFERENCES public."Colors" (c_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Medias"
    ADD FOREIGN KEY (m_product_id)
    REFERENCES public."Products" (p_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrderTransactions"
    ADD FOREIGN KEY (ot_o_id)
    REFERENCES public."Orders" (o_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;